### ISSUE TITLE
add HTTPS to the documentation site

### ISSUE THREAD

**Issue by mrjones2014** [Dan503/gutter-grid#3]
You could just use GitHub pages. Not having an HTTPS secured site almost made me ignore this package.

**Comment by Dan503** [comment]
I'm actually planning on switching the site over to using netlify within 30 days which will automatically also provide https.

I don't want to have to pay the hosting fees for the domain name anymore.

The documentation site doesn't really have any forms on it so I didn't think it is risky using the current site as it is right now.

The code base is a few years old now. It also has a complex custom gulp build process behind it. I need to upgrade the gulp files to Gulp 4 before I can publish to netlify. The build on master branch is failing with loads of out of date node module dependencies.

Note, it's the dev dependencies that are out of date. The only actual dependency is mq-scss and it is using the latest version of that.

**Comment by mrjones2014** [comment]
This package saved me a lot of headache, so I'm happy to help out and submit PRs if you create issues for tasks.

**Comment by Dan503** [comment]
Glad you like the package 😊

> I'm happy to help out and submit PRs if you create issues for tasks.

Thanks for the offer. This specific task is very difficult and complex though. It's something I need to do myself. I've already made a start on the conversion in the Gulp 4 branch.

**Comment by Dan503** [comment]
Documentation website is now available here:
https://dan503.github.io/gutter-grid/

I tried publishing to Netlify but for some reason Netlify was struggling to compile the pug files even though they were compiling  just fine locally.

I decided to give up on Netlify and just go with GitHub pages. It's not as nice but at least I don't have to worry about the build failing since the live site is stored as static files in Git.
